### ISSUE TITLE
Impossible to clear indices via CLI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-symfony#12]
- I ran a local MS instance with an index named `indexUID` containing books with a `title`
- I created a new Symfony project
- I added:
```bash
MEILISEARCH_URL=http://127.0.0.1:7700
MEILISEARCH_API_KEY=masterKey
```
in my project
- I added this file (`/config/package/meili_search.yaml`) in my project:
```yml
meili_search:
     indices:
          -   name: indexUID
               class: App\Entity\Book
               enable_serializer_groups: true
```
(I've also created an `src/Entity/Book.php` file following this [part of the docs](https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data#using-annotations))
- Following [this part of the docs](https://github.com/meilisearch/meilisearch-symfony/wiki/index-data-into-meilisearch#removing-manually), I did:
```bash
$ php bin/console meili:clear
```
And I got:
```bash
Index indexUID  couldn't be cleared
Done!
```

The index was indeed not removed.
Plus, an empty `dev_indexUID` was created in my MeiliSearch instance.

Versions:
- MeiliSearch `v0.12.0`
- meilisearch/search-bundle `v0.2.0`
- Symfony `v4.17.0`
