### ISSUE TITLE
Command meili:create doesn't create index without settings

### ISSUE THREAD

**Issue by reflexator** [meilisearch/meilisearch-symfony#176]
**Description**
Running php bin/console meili:create - didnt create index when no settings is present in configuration aka:

```
    indices:
        - name: shopping_gallery_tenant
          class: App\Entity\ShoppingGalleryTenant
          enable_serializer_groups:  true
```

**Expected behavior**
Index is created when no settings is present

**Current behavior**
Index is not created

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: v:0.23.1
- meilisearch-symfony version: v0.7.2
