### ISSUE TITLE
Add support to the typo tolerance customization

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-symfony#179]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Related to:
- parent issue: https://github.com/meilisearch/integration-guides/issues/190
- specification: https://github.com/meilisearch/specifications/pull/117

----

⚠️ The https://github.com/meilisearch/meilisearch-php/pull/312 should be finished before starting this issue!

Add a `typo_tolerance` index settings resource to manage customization of the typo tolerance feature at the index level.

```yml
# meili_search.yaml
meili_search:
  indices:
    - name: posts
      class: App\Entity\Post
      settings:
        # attributesForFaceting: ['genres', 'publishedAt']
        typoTolerance: 
          enabled: true
          disableOnAttributes: ['title']
          disableOnWords: ['york']
          minWordSizeForTypos: 
            oneTypo: 5
            twoTypos: 9
```

More information about what the typo-tolerance field does could be [checked in the spec.](https://github.com/meilisearch/specifications/pull/117)

You could check the other customization methods for reference like: `synonyms`.

TODO:
- [ ] Add the `typo_tolerance` configuration
- [ ] Add tests
