### ISSUE TITLE
Use of `NormalizableInterface` does not seem to work

### ISSUE THREAD

**Issue by YummYume** [meilisearch/meilisearch-symfony#228]
**Description**
Hello. Thank you for making this bundle, it works like a charm.

I had been using the `#[Groups('searchable')]` to filter the different fields I needed Meilisearch to index and it worked really well. But I now need a more advanced usage with nested relations and decided to use the `normalize()` function by implementing `NormalizableInterface` in my entity, as stated [in the doc](https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data#using-normalize). However, this does not seem to work at all. The `normalize()` function is simply never called and it keeps trying to serialise my whole entity instead.

My entity :

```php
<?php

namespace App\Entity;

// ...
use Symfony\Component\Serializer\Normalizer\NormalizableInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

#[ORM\Entity(repositoryClass: ProfileRepository::class)]
class Profile implements NormalizableInterface
{
    // ...

    public function normalize(NormalizerInterface $normalizer, ?string $format = null, array $context = []): array|string|int|float|bool
    {
        return [
            // ...
        ];
    }
}
```

My config : 

```yaml
meilisearch:
    url: '%env(MEILISEARCH_URL)%'
    api_key: '%env(MEILISEARCH_MASTER_KEY)%'
    prefix: '%env(APP_ENV)%_'
    indices:
        - name: profiles
          class: App\Entity\Profile
          index_if: isIndexable
          settings:
              searchableAttributes: ['username', 'slug', 'description', 'picture']
```

I don't know if I'm simply missing something, or if additional configuration is perhaps required.

**Expected behavior**
I would expect this bundle to use the `normalize` function declared in my entity.

**Current behavior**
My entire entity is getting serialized instead and throws a circular reference exception.

**Screenshots or Logs**
![circular_reference_exception](https://user-images.githubusercontent.com/61044908/218558346-333370ed-9526-4f05-b774-0136d3587d18.png)

**Environment (please complete the following information):**
- OS: Alpine Linux v3.17.2
- Meilisearch version: v1.0
- meilisearch-symfony version: v0.10.1
