### ISSUE TITLE
Allow configurable serialization group(s)

### ISSUE THREAD

**Issue by tacman** [meilisearch/meilisearch-symfony#238]
Currently the serialization groups support requires a group of 'searchable' (Searchable::NORMALIZATION_GROUP).  

Since I already have a serialization group set up on my entities, I'd like to use that.  Actually, I'd like to use more than one, so that I can say something like

```yaml
    indices:
        - name: movies
          class: App\Entity\Movie
          enable_serializer_groups: true
          serializer_groups: ['movie.read','movie.export']
```

On an unrelated note, meilisearch rocks!  I can't wait to start using it in production.
