### ISSUE TITLE
Import of Mongo ODM entities fails 

### ISSUE THREAD

**Issue by Evoolo** [meilisearch/meilisearch-symfony#311]
**Description**
I added some entities to my meilisearch config and then run  `php bin/console meilisearch:import`.
All MySQL entities are getting imported correctly. As soon as I reach the first mongo-odm entity, it fails with 

> In MeilisearchImportCommand.php line 115: Call to a member function getRepository() on null 

While this package loads  only the Doctrine\Persistence\ManagerRegistry wich can not be used for mongo-aod, I think this package is not compatible with the mongo-odm implementation. 

Also when I try to persist a new entity, I get this error:

> {
    "code": 500,
    "message": "Meilisearch\\Bundle\\SearchableEntity::__construct(): Argument #3 ($entityMetadata) must be of type Doctrine\\ORM\\Mapping\\ClassMetadata, Doctrine\\ODM\\MongoDB\\Mapping\\ClassMetadata given, called in /home/vagrant/code/chgtwy_api/vendor/meilisearch/search-bundle/src/Services/MeilisearchService.php on line 318"
}

**Expected behavior**
creating a search index for all entities

**Current behavior**
only creates an index for MySQL entities and throws an error on mongo-odm entities

> In MeilisearchImportCommand.php line 115: Call to a member function getRepository() on null 

**Screenshots or Logs**
```
// config/packages/meilisearch.yaml
meilisearch:
    url: '%env(MEILISEARCH_URL)%' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    indices:
        - name: account
          class: App\Entity\Account\Account
          enable_serializer_groups: true
        - name: log_request
          class: App\Entity\LogRequest
          enable_serializer_groups: true
        - name: bsc_webhook
          class: App\Document\BinanceSmartChain\Webhook
          enable_serializer_groups: true
        - name: bsc_notification
          class: App\Document\BinanceSmartChain\Notification
          enable_serializer_groups: true
```

```
<?php

namespace App\Document\BinanceSmartChain;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

#[MongoDb\Document(db: 'IPN', collection: 'ipn_bsc_main_send', repositoryClass: \App\Repository\BinanceSmartChain\NotificationRepository::class)]
class Notification
{

    #[MongoDB\Id]
    protected $id;

    #[MongoDB\Field(type: 'string')]
    protected $txid;

    #[MongoDB\Field(type: 'string')]
    protected $webhook_id;

    #[MongoDB\Field(type: 'string')]
    protected $type;
...

```
          

**Environment (please complete the following information):**
- OS: Ubuntu 22.04
- Meilisearch version: v1.5.0
- meilisearch-symfony version: v1.0.0
