### ISSUE TITLE
Cannot define "indices.settings" of MeilisearchConfig with PHP

### ISSUE THREAD

**Issue by pan93412** [meilisearch/meilisearch-symfony#369]
**Description**

I am migrating my Symfony config to use type-safe PHP-based ConfigBuilder.

However, the definition of Meilisearch config seems having a problem, which makes the following code not working:

```php
    $meiliSearchConfig
        ->indices()
            ->settings([
                'filterableAttributes' => [
                    'type',
                    'difficulty',
                ],
                'sortableAttributes' => [
                    'id',
                ],
            ]);
```

It says:

```
The following keys are not supported by "Symfony\Config\MeiliSearch\IndicesConfig\SettingsConfig": filterableAttributes, sortableAttributes  
```

**Expected behavior**

I can define settings as what I did in my YAML config.

```yaml
meilisearch:
  indices:
    - settings:
        filterableAttributes:
          - type
          - difficulty
        sortableAttributes:
          - id
```

**Current behavior**

```
In FileLoader.php line 177:
                                                                                                                                                                                  
  The following keys are not supported by "Symfony\Config\MeiliSearch\IndicesConfig\SettingsConfig": filterableAttributes, sortableAttributes in /Volumes/Dev/ResearchProject/le  
  ts-php/app-sf/config/packages/meilisearch.php (which is being imported from "/Volumes/Dev/ResearchProject/lets-php/app-sf/src/Kernel.php").                                     
                                                                                                                                                                                  

In SettingsConfig.php line 16:
                                                                                                                                               
  The following keys are not supported by "Symfony\Config\MeiliSearch\IndicesConfig\SettingsConfig": filterableAttributes, sortableAttributes  
```

**Screenshots or Logs**

![CleanShot 2024-12-03 at 11 09 19@2x](https://github.com/user-attachments/assets/749d7253-932c-494b-aeac-328ba01ddbc5)

**Environment (please complete the following information):**
- OS: macOS
- Meilisearch version: N/A
- meilisearch-symfony version: dev-main (d46b2da1865ef228aaca67eeac9e6851022dbeaf)

**Comment by Tsolmonx** [comment]
this happens to my yaml configuration too.
```
meilisearch:
    url: '%env(MEILISEARCH_URL)%' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    doctrineSubscribedEvents: ['preRemove']
    batchSize: 250
    indices:
        -   name: products
            class: App\Entity\Product\Product
            index_if: isIndexable
            enable_serializer_groups: true
            serializer_groups: ['shop:product:searchable']
            settings:
                filterableAttributes: ['productTaxons','brand','featured','attributes','mainTaxon','code','tags']
                searchableAttributes: ['translations']
                sortableAttributes: ['createdAt','variants']

```
when i try to create indexes with bin/console meili:create i got follwing error

In SettingsUpdater.php line 73:

  Exception::__construct(): Argument #1 ($message) must be of type string, array given
but when i remove the settings it just creates without a problem
