### ISSUE TITLE
Enable multiple indices per entity

### ISSUE THREAD

**Issue by aarsla** [meilisearch/meilisearch-symfony#372]
**Description**
It would be useful to have the possibility of creating multiple idices per entity.

**Basic example**
```
meilisearch:
  indices:
    - name: supported
      class: App\Entity\MyEntity
      index_if: isSupported
    - name: completed
      class: App\Entity\MyEntity
      index_if: isCompleted
```
Currently `private function setIndexIfMapping(): void` of MeilisearchService.php maps only one IndexIfMapping per entity.
